# Generated by Django 4.1.7 on 2023-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbinglofc', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('message', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
