# Generated by Django 4.1.7 on 2023-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbinglofc', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
