# Generated by Django 4.1.7 on 2023-08-19 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mbinglofc', '0004_remove_contact_number_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
