# Generated by Django 4.1.7 on 2023-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbinglofc', '0005_alter_blogpost_author1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('match_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
