# Generated by Django 4.1.7 on 2023-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbinglofc', '0006_upcomingmatches_alter_blogpost_author1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingmatches',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
